#!/bin/bash

# Google Workspace SMTP Configuration Script for Supabase
# Generated by: integrator-permanent agent
# Project: ContractorAI2

set -e

echo "🔧 Google Workspace SMTP Configuration for Supabase"
echo "=================================================="
echo ""

# Colors
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
RED='\033[0;31m'
NC='\033[0m' # No Color

# Supabase project details
SUPABASE_REF="ujhgwcurllkkeouzwvgk"
SUPABASE_URL="https://YOUR_PROJECT_REF.supabase.co"

echo -e "${YELLOW}📋 Prerequisites Check${NC}"
echo "Before proceeding, ensure you have:"
echo "  ✓ Google Workspace account with admin access"
echo "  ✓ 2FA enabled on your Google account"
echo "  ✓ Generated Google App Password"
echo "  ✓ Supabase project access"
echo ""

read -p "Do you have all prerequisites ready? (y/n): " prerequisites
if [[ $prerequisites != "y" ]]; then
    echo -e "${RED}❌ Please complete prerequisites first.${NC}"
    echo ""
    echo "Follow the guide at:"
    echo "  docs/GOOGLE-WORKSPACE-SMTP-SETUP.md"
    exit 1
fi

echo ""
echo -e "${GREEN}✅ Prerequisites confirmed!${NC}"
echo ""

# Get configuration details
echo -e "${YELLOW}📝 Enter Configuration Details${NC}"
echo ""

read -p "Google Workspace Email (e.g., admin@yourdomain.com): " SMTP_EMAIL
read -p "Google App Password (16 characters): " -s SMTP_PASSWORD
echo ""
read -p "Sender Name (e.g., ContractorAI): " SENDER_NAME

# Remove spaces from app password
SMTP_PASSWORD_CLEAN=$(echo "$SMTP_PASSWORD" | tr -d ' ')

# SMTP server selection
echo ""
echo -e "${YELLOW}🌐 Select SMTP Server${NC}"
echo "1) smtp.gmail.com (port 587) - Recommended"
echo "2) smtp.gmail.com (port 465) - SSL"
echo "3) smtp-relay.gmail.com (port 465) - Workspace Only"
read -p "Choose option (1-3): " smtp_option

case $smtp_option in
    1)
        SMTP_HOST="smtp.gmail.com"
        SMTP_PORT=587
        ;;
    2)
        SMTP_HOST="smtp.gmail.com"
        SMTP_PORT=465
        ;;
    3)
        SMTP_HOST="smtp-relay.gmail.com"
        SMTP_PORT=465
        ;;
    *)
        echo -e "${RED}❌ Invalid option${NC}"
        exit 1
        ;;
esac

echo ""
echo -e "${GREEN}📋 Configuration Summary:${NC}"
echo "  SMTP Host: $SMTP_HOST"
echo "  SMTP Port: $SMTP_PORT"
echo "  SMTP User: $SMTP_EMAIL"
echo "  Sender: $SENDER_NAME <$SMTP_EMAIL>"
echo ""

read -p "Proceed with configuration? (y/n): " confirm
if [[ $confirm != "y" ]]; then
    echo -e "${YELLOW}⚠️  Configuration cancelled.${NC}"
    exit 0
fi

echo ""
echo -e "${YELLOW}🔧 Configuring Supabase...${NC}"
echo ""

# Note: This script outputs the configuration
# You need to manually enter these in Supabase Dashboard
# Supabase doesn't provide a CLI command for SMTP configuration yet

echo -e "${GREEN}✅ Configuration Details Generated!${NC}"
echo ""
echo "=================================================="
echo "📋 NEXT STEPS:"
echo "=================================================="
echo ""
echo "1. Go to Supabase Dashboard:"
echo "   https://supabase.com/dashboard/project/$SUPABASE_REF/settings/auth"
echo ""
echo "2. Navigate to: SMTP Settings"
echo ""
echo "3. Enable Custom SMTP and enter:"
echo ""
echo "   SMTP Host: $SMTP_HOST"
echo "   SMTP Port: $SMTP_PORT"
echo "   SMTP Username: $SMTP_EMAIL"
echo "   SMTP Password: [paste your app password]"
echo "   Sender Email: $SMTP_EMAIL"
echo "   Sender Name: $SENDER_NAME"
echo ""
echo "4. Click 'Save'"
echo ""
echo "5. Test with the diagnostic tool:"
echo "   open tests/test-email-auth.html"
echo ""
echo "=================================================="
echo ""

# Save configuration to .env.local (without password)
echo -e "${YELLOW}💾 Saving configuration reference...${NC}"

cat > .env.smtp.example << EOF
# Google Workspace SMTP Configuration
# Generated: $(date)
# DO NOT COMMIT THIS FILE WITH ACTUAL CREDENTIALS

SMTP_HOST=$SMTP_HOST
SMTP_PORT=$SMTP_PORT
SMTP_USER=$SMTP_EMAIL
SMTP_PASS=your_google_app_password_here
SMTP_SENDER_NAME=$SENDER_NAME
SMTP_SENDER_EMAIL=$SMTP_EMAIL

# Supabase Project
SUPABASE_URL=$SUPABASE_URL
SUPABASE_REF=$SUPABASE_REF
EOF

echo -e "${GREEN}✅ Configuration saved to: .env.smtp.example${NC}"
echo ""
echo -e "${YELLOW}⚠️  IMPORTANT: Store your app password securely!${NC}"
echo ""
echo "Configuration complete! 🎉"
echo ""
